#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-s2
Version  : 1.0.6
Release  : 3
URL      : https://cran.r-project.org/src/contrib/s2_1.0.6.tar.gz
Source0  : https://cran.r-project.org/src/contrib/s2_1.0.6.tar.gz
Summary  : Spherical Geometry Operators Using the S2 Geometry Library
Group    : Development/Tools
License  : Apache-2.0
Requires: R-s2-lib = %{version}-%{release}
Requires: R-Rcpp
Requires: R-wk
BuildRequires : R-Rcpp
BuildRequires : R-wk
BuildRequires : buildreq-R
BuildRequires : openssl-dev

%description
the sphere. High-performance constructors and exporters provide high compatibility
    with existing spatial packages, transformers construct new geometries from existing
    geometries, predicates provide a means to select geometries based on spatial 
    relationships, and accessors extract information about geometries.

%package lib
Summary: lib components for the R-s2 package.
Group: Libraries

%description lib
lib components for the R-s2 package.


%prep
%setup -q -c -n s2
cd %{_builddir}/s2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1623943828

%install
export SOURCE_DATE_EPOCH=1623943828
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library s2
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library s2
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library s2
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc s2 || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/s2/DESCRIPTION
/usr/lib64/R/library/s2/INDEX
/usr/lib64/R/library/s2/Meta/Rd.rds
/usr/lib64/R/library/s2/Meta/data.rds
/usr/lib64/R/library/s2/Meta/features.rds
/usr/lib64/R/library/s2/Meta/hsearch.rds
/usr/lib64/R/library/s2/Meta/links.rds
/usr/lib64/R/library/s2/Meta/nsInfo.rds
/usr/lib64/R/library/s2/Meta/package.rds
/usr/lib64/R/library/s2/NAMESPACE
/usr/lib64/R/library/s2/NEWS.md
/usr/lib64/R/library/s2/R/s2
/usr/lib64/R/library/s2/R/s2.rdb
/usr/lib64/R/library/s2/R/s2.rdx
/usr/lib64/R/library/s2/data/Rdata.rdb
/usr/lib64/R/library/s2/data/Rdata.rds
/usr/lib64/R/library/s2/data/Rdata.rdx
/usr/lib64/R/library/s2/help/AnIndex
/usr/lib64/R/library/s2/help/aliases.rds
/usr/lib64/R/library/s2/help/figures/rc300.png
/usr/lib64/R/library/s2/help/paths.rds
/usr/lib64/R/library/s2/help/s2.rdb
/usr/lib64/R/library/s2/help/s2.rdx
/usr/lib64/R/library/s2/html/00Index.html
/usr/lib64/R/library/s2/html/R.css
/usr/lib64/R/library/s2/include/cpp-compat.h
/usr/lib64/R/library/s2/include/s2/_fp_contract_off.h
/usr/lib64/R/library/s2/include/s2/base/casts.h
/usr/lib64/R/library/s2/include/s2/base/commandlineflags.h
/usr/lib64/R/library/s2/include/s2/base/integral_types.h
/usr/lib64/R/library/s2/include/s2/base/log_severity.h
/usr/lib64/R/library/s2/include/s2/base/logging.h
/usr/lib64/R/library/s2/include/s2/base/mutex.h
/usr/lib64/R/library/s2/include/s2/base/port.h
/usr/lib64/R/library/s2/include/s2/base/spinlock.h
/usr/lib64/R/library/s2/include/s2/base/stringprintf.h
/usr/lib64/R/library/s2/include/s2/base/strtoint.h
/usr/lib64/R/library/s2/include/s2/base/timer.h
/usr/lib64/R/library/s2/include/s2/encoded_s2cell_id_vector.h
/usr/lib64/R/library/s2/include/s2/encoded_s2point_vector.h
/usr/lib64/R/library/s2/include/s2/encoded_s2shape_index.h
/usr/lib64/R/library/s2/include/s2/encoded_string_vector.h
/usr/lib64/R/library/s2/include/s2/encoded_uint_vector.h
/usr/lib64/R/library/s2/include/s2/id_set_lexicon.h
/usr/lib64/R/library/s2/include/s2/mutable_s2shape_index.h
/usr/lib64/R/library/s2/include/s2/r1interval.h
/usr/lib64/R/library/s2/include/s2/r2.h
/usr/lib64/R/library/s2/include/s2/r2rect.h
/usr/lib64/R/library/s2/include/s2/s1angle.h
/usr/lib64/R/library/s2/include/s2/s1chord_angle.h
/usr/lib64/R/library/s2/include/s2/s1interval.h
/usr/lib64/R/library/s2/include/s2/s2boolean_operation.h
/usr/lib64/R/library/s2/include/s2/s2builder.h
/usr/lib64/R/library/s2/include/s2/s2builder_graph.h
/usr/lib64/R/library/s2/include/s2/s2builder_layer.h
/usr/lib64/R/library/s2/include/s2/s2builderutil_closed_set_normalizer.h
/usr/lib64/R/library/s2/include/s2/s2builderutil_find_polygon_degeneracies.h
/usr/lib64/R/library/s2/include/s2/s2builderutil_graph_shape.h
/usr/lib64/R/library/s2/include/s2/s2builderutil_lax_polygon_layer.h
/usr/lib64/R/library/s2/include/s2/s2builderutil_s2point_vector_layer.h
/usr/lib64/R/library/s2/include/s2/s2builderutil_s2polygon_layer.h
/usr/lib64/R/library/s2/include/s2/s2builderutil_s2polyline_layer.h
/usr/lib64/R/library/s2/include/s2/s2builderutil_s2polyline_vector_layer.h
/usr/lib64/R/library/s2/include/s2/s2builderutil_snap_functions.h
/usr/lib64/R/library/s2/include/s2/s2builderutil_testing.h
/usr/lib64/R/library/s2/include/s2/s2cap.h
/usr/lib64/R/library/s2/include/s2/s2cell.h
/usr/lib64/R/library/s2/include/s2/s2cell_id.h
/usr/lib64/R/library/s2/include/s2/s2cell_index.h
/usr/lib64/R/library/s2/include/s2/s2cell_union.h
/usr/lib64/R/library/s2/include/s2/s2centroids.h
/usr/lib64/R/library/s2/include/s2/s2closest_cell_query.h
/usr/lib64/R/library/s2/include/s2/s2closest_cell_query_base.h
/usr/lib64/R/library/s2/include/s2/s2closest_edge_query.h
/usr/lib64/R/library/s2/include/s2/s2closest_edge_query_base.h
/usr/lib64/R/library/s2/include/s2/s2closest_edge_query_testing.h
/usr/lib64/R/library/s2/include/s2/s2closest_point_query.h
/usr/lib64/R/library/s2/include/s2/s2closest_point_query_base.h
/usr/lib64/R/library/s2/include/s2/s2contains_point_query.h
/usr/lib64/R/library/s2/include/s2/s2contains_vertex_query.h
/usr/lib64/R/library/s2/include/s2/s2convex_hull_query.h
/usr/lib64/R/library/s2/include/s2/s2coords.h
/usr/lib64/R/library/s2/include/s2/s2coords_internal.h
/usr/lib64/R/library/s2/include/s2/s2crossing_edge_query.h
/usr/lib64/R/library/s2/include/s2/s2debug.h
/usr/lib64/R/library/s2/include/s2/s2distance_target.h
/usr/lib64/R/library/s2/include/s2/s2earth.h
/usr/lib64/R/library/s2/include/s2/s2edge_clipping.h
/usr/lib64/R/library/s2/include/s2/s2edge_crosser.h
/usr/lib64/R/library/s2/include/s2/s2edge_crossings.h
/usr/lib64/R/library/s2/include/s2/s2edge_crossings_internal.h
/usr/lib64/R/library/s2/include/s2/s2edge_distances.h
/usr/lib64/R/library/s2/include/s2/s2edge_tessellator.h
/usr/lib64/R/library/s2/include/s2/s2edge_vector_shape.h
/usr/lib64/R/library/s2/include/s2/s2error.h
/usr/lib64/R/library/s2/include/s2/s2furthest_edge_query.h
/usr/lib64/R/library/s2/include/s2/s2latlng.h
/usr/lib64/R/library/s2/include/s2/s2latlng_rect.h
/usr/lib64/R/library/s2/include/s2/s2latlng_rect_bounder.h
/usr/lib64/R/library/s2/include/s2/s2lax_loop_shape.h
/usr/lib64/R/library/s2/include/s2/s2lax_polygon_shape.h
/usr/lib64/R/library/s2/include/s2/s2lax_polyline_shape.h
/usr/lib64/R/library/s2/include/s2/s2loop.h
/usr/lib64/R/library/s2/include/s2/s2loop_measures.h
/usr/lib64/R/library/s2/include/s2/s2max_distance_targets.h
/usr/lib64/R/library/s2/include/s2/s2measures.h
/usr/lib64/R/library/s2/include/s2/s2metrics.h
/usr/lib64/R/library/s2/include/s2/s2min_distance_targets.h
/usr/lib64/R/library/s2/include/s2/s2padded_cell.h
/usr/lib64/R/library/s2/include/s2/s2point.h
/usr/lib64/R/library/s2/include/s2/s2point_compression.h
/usr/lib64/R/library/s2/include/s2/s2point_index.h
/usr/lib64/R/library/s2/include/s2/s2point_region.h
/usr/lib64/R/library/s2/include/s2/s2point_span.h
/usr/lib64/R/library/s2/include/s2/s2point_vector_shape.h
/usr/lib64/R/library/s2/include/s2/s2pointutil.h
/usr/lib64/R/library/s2/include/s2/s2polygon.h
/usr/lib64/R/library/s2/include/s2/s2polyline.h
/usr/lib64/R/library/s2/include/s2/s2polyline_alignment.h
/usr/lib64/R/library/s2/include/s2/s2polyline_alignment_internal.h
/usr/lib64/R/library/s2/include/s2/s2polyline_measures.h
/usr/lib64/R/library/s2/include/s2/s2polyline_simplifier.h
/usr/lib64/R/library/s2/include/s2/s2predicates.h
/usr/lib64/R/library/s2/include/s2/s2predicates_internal.h
/usr/lib64/R/library/s2/include/s2/s2projections.h
/usr/lib64/R/library/s2/include/s2/s2r2rect.h
/usr/lib64/R/library/s2/include/s2/s2region.h
/usr/lib64/R/library/s2/include/s2/s2region_coverer.h
/usr/lib64/R/library/s2/include/s2/s2region_intersection.h
/usr/lib64/R/library/s2/include/s2/s2region_term_indexer.h
/usr/lib64/R/library/s2/include/s2/s2region_union.h
/usr/lib64/R/library/s2/include/s2/s2shape.h
/usr/lib64/R/library/s2/include/s2/s2shape_index.h
/usr/lib64/R/library/s2/include/s2/s2shape_index_buffered_region.h
/usr/lib64/R/library/s2/include/s2/s2shape_index_measures.h
/usr/lib64/R/library/s2/include/s2/s2shape_index_region.h
/usr/lib64/R/library/s2/include/s2/s2shape_measures.h
/usr/lib64/R/library/s2/include/s2/s2shapeutil_build_polygon_boundaries.h
/usr/lib64/R/library/s2/include/s2/s2shapeutil_coding.h
/usr/lib64/R/library/s2/include/s2/s2shapeutil_contains_brute_force.h
/usr/lib64/R/library/s2/include/s2/s2shapeutil_count_edges.h
/usr/lib64/R/library/s2/include/s2/s2shapeutil_edge_iterator.h
/usr/lib64/R/library/s2/include/s2/s2shapeutil_get_reference_point.h
/usr/lib64/R/library/s2/include/s2/s2shapeutil_range_iterator.h
/usr/lib64/R/library/s2/include/s2/s2shapeutil_shape_edge.h
/usr/lib64/R/library/s2/include/s2/s2shapeutil_shape_edge_id.h
/usr/lib64/R/library/s2/include/s2/s2shapeutil_testing.h
/usr/lib64/R/library/s2/include/s2/s2shapeutil_visit_crossing_edge_pairs.h
/usr/lib64/R/library/s2/include/s2/s2testing.h
/usr/lib64/R/library/s2/include/s2/s2text_format.h
/usr/lib64/R/library/s2/include/s2/s2wedge_relations.h
/usr/lib64/R/library/s2/include/s2/sequence_lexicon.h
/usr/lib64/R/library/s2/include/s2/strings/ostringstream.h
/usr/lib64/R/library/s2/include/s2/strings/serialize.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/algorithm/algorithm.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/base/attributes.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/base/casts.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/base/config.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/base/dynamic_annotations.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/base/internal/atomic_hook.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/base/internal/identity.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/base/internal/inline_variable.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/base/internal/invoke.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/base/internal/raw_logging.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/base/internal/throw_delegate.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/base/internal/unaligned_access.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/base/log_severity.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/base/macros.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/base/optimization.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/base/policy_checks.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/base/port.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/base/thread_annotations.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/container/fixed_array.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/container/inlined_vector.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/container/internal/compressed_tuple.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/container/internal/container_memory.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/container/internal/layout.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/memory/memory.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/meta/type_traits.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/numeric/int128.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/numeric/int128_have_intrinsic.inc
/usr/lib64/R/library/s2/include/s2/third_party/absl/numeric/int128_no_intrinsic.inc
/usr/lib64/R/library/s2/include/s2/third_party/absl/strings/ascii.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/strings/ascii_ctype.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/strings/internal/bits.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/strings/internal/memutil.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/strings/internal/resize_uninitialized.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/strings/match.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/strings/numbers.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/strings/str_cat.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/strings/str_join.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/strings/str_split.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/strings/string_view.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/strings/strip.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/types/span.h
/usr/lib64/R/library/s2/include/s2/third_party/absl/utility/utility.h
/usr/lib64/R/library/s2/include/s2/util/bits/bit-interleave.h
/usr/lib64/R/library/s2/include/s2/util/bits/bits.h
/usr/lib64/R/library/s2/include/s2/util/coding/coder.h
/usr/lib64/R/library/s2/include/s2/util/coding/nth-derivative.h
/usr/lib64/R/library/s2/include/s2/util/coding/transforms.h
/usr/lib64/R/library/s2/include/s2/util/coding/varint.h
/usr/lib64/R/library/s2/include/s2/util/endian/endian.h
/usr/lib64/R/library/s2/include/s2/util/gtl/btree.h
/usr/lib64/R/library/s2/include/s2/util/gtl/btree_container.h
/usr/lib64/R/library/s2/include/s2/util/gtl/btree_map.h
/usr/lib64/R/library/s2/include/s2/util/gtl/btree_set.h
/usr/lib64/R/library/s2/include/s2/util/gtl/compact_array.h
/usr/lib64/R/library/s2/include/s2/util/gtl/container_logging.h
/usr/lib64/R/library/s2/include/s2/util/gtl/dense_hash_set.h
/usr/lib64/R/library/s2/include/s2/util/gtl/densehashtable.h
/usr/lib64/R/library/s2/include/s2/util/gtl/hashtable_common.h
/usr/lib64/R/library/s2/include/s2/util/gtl/layout.h
/usr/lib64/R/library/s2/include/s2/util/gtl/legacy_random_shuffle.h
/usr/lib64/R/library/s2/include/s2/util/hash/mix.h
/usr/lib64/R/library/s2/include/s2/util/math/exactfloat/exactfloat.h
/usr/lib64/R/library/s2/include/s2/util/math/mathutil.h
/usr/lib64/R/library/s2/include/s2/util/math/matrix3x3.h
/usr/lib64/R/library/s2/include/s2/util/math/vector.h
/usr/lib64/R/library/s2/include/s2/util/math/vector3_hash.h
/usr/lib64/R/library/s2/include/s2/util/units/length-units.h
/usr/lib64/R/library/s2/include/s2/util/units/physical-units.h
/usr/lib64/R/library/s2/include/s2/value_lexicon.h
/usr/lib64/R/library/s2/tests/area.R
/usr/lib64/R/library/s2/tests/area.Rout
/usr/lib64/R/library/s2/tests/testthat.R
/usr/lib64/R/library/s2/tests/testthat/test-data.R
/usr/lib64/R/library/s2/tests/testthat/test-s2-accessors.R
/usr/lib64/R/library/s2/tests/testthat/test-s2-bounds.R
/usr/lib64/R/library/s2/tests/testthat/test-s2-cell.R
/usr/lib64/R/library/s2/tests/testthat/test-s2-constructors-formatters.R
/usr/lib64/R/library/s2/tests/testthat/test-s2-earth.R
/usr/lib64/R/library/s2/tests/testthat/test-s2-geography.R
/usr/lib64/R/library/s2/tests/testthat/test-s2-lnglat.R
/usr/lib64/R/library/s2/tests/testthat/test-s2-matrix.R
/usr/lib64/R/library/s2/tests/testthat/test-s2-options.R
/usr/lib64/R/library/s2/tests/testthat/test-s2-point.R
/usr/lib64/R/library/s2/tests/testthat/test-s2-predicates.R
/usr/lib64/R/library/s2/tests/testthat/test-s2-transformers.R
/usr/lib64/R/library/s2/tests/testthat/test-s2-xptr.R
/usr/lib64/R/library/s2/tests/testthat/test-utils.R
/usr/lib64/R/library/s2/tests/testthat/test-vctrs.R
/usr/lib64/R/library/s2/tests/testthat/test-wk-utils.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/s2/libs/s2.so
/usr/lib64/R/library/s2/libs/s2.so.avx2
